package exceptionHandling;
import java.util.Arrays;
import java.util.Scanner;
public class ArrayIndexOutOfBound
{
// package trainingProjects;public class ArrayIndexOutOfBoundsException {
public static void main(String args[])
{
Scanner sc = new Scanner(System.in);
System.out.println("enter the elements: ");
int arr[]= new int[5];
//for loop iterates from 0 to 5 (length of array)
for (int i = 0; i < arr.length; i++)
{
arr[i]=sc.nextInt();

}
System.out.println(Arrays.toString(arr));
System.out.println("\n ");
System.out.println("enter the index number:");
try
{
int n = sc.nextInt();
System.out.println(arr[n]);
}
catch(ArrayIndexOutOfBoundsException a)
{
System.out.println("Index number should be with in the size:");
}
//when ‘i’ reaches 5, it becomes invalid index and exception will be thrown
}
}